title:              ListValet
description:        Connecting Owners and Sellers. Returning value to used items.
author:             Start Bootstrap
baseurl:            "/"
url:                "www.listvalet.com"
port: 4002
# Social Profiles
twitter_username:   listvalet
github_username:    listvalet
facebook_username:  listvalet
instagram_username:  listvalet

# Add your google-analytics ID here to activate google analytics
# google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code
theme: jekyll-theme-clean-blog
# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/seller/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
collections:
  owner:
    output: true
    permalink: /:collection/:title
  seller:
    output: true
    permalink: /:collection/:title
